sudo: false
language: rust

cache:
  cargo: true

os:
  - linux

# If you change this, you must also change Getting_Started.md, Makefile.common,
# and Vagrantfile.
rust:
  - nightly-2018-06-26

before_script:
  - npm install -g markdown-toc

script:
  - export PATH=$HOME/.cargo/bin:$PATH
  - make ci-travis

